using thing
letsbuilda/larkbot pull request #10
Opened 2023-01-26 07:51 UTC by SomeHybrid

fixing #9 (also i didnt test it bc circular imports shit and docker brokey)

2023-01-26 14:40 UTC, shenanigansd commented on src/bot/exts/fun/uwu.py
> +async def setup(bot: commands.Bot) -> None:
```suggestion
async def setup(bot: Bot) -> None:
```
This `Bot` is the subclass defined in `bot/bot.py`, not the base Discord.py `commands.bot`.

2023-01-26 14:44 UTC, shenanigansd requested changes
Everything looks good at first glance.
You'll also need to add the new dependency to the `pyproject.toml`

2023-01-27 00:35 UTC, Robin5605 approved these changes

2023-01-27 00:35 UTC, Robin5605 commented on src/bot/exts/fun/uwu.py
>          await ctx.send(content=converted_text, embed=embed)
See above
```suggestion
        await ctx.send(content=converted_text, embeds=embeds)
```

2023-01-27 00:35 UTC, Robin5605 commented on src/bot/exts/fun/uwu.py
> +            embed = messages.convert_embed(imsosorry.uwuify, embeds[0])
Handle multiple embeds
```suggestion
            embeds = [messages.convert_embed(imsosorry.uwuify, embed) for embed in embeds]
```

2023-01-27 00:35 UTC, Robin5605 commented on src/bot/exts/fun/uwu.py
>          if embeds:
No longer needed

2023-01-27 07:07 UTC, closed without merging